title: 🇺🇸 Flag Status Monitor
description: Real-time flag status monitor for the United States
baseurl: /flag-status-monitor
url: https://jacob-booth.github.io
theme: null
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor