source "https://rubygems.org"

gem "jekyll", "~> 3.9.3"
gem "github-pages", "~> 228"
gem "webrick", "~> 1.8"
gem "jekyll-theme-minimal"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end