name: Auto Update and Deploy GitHub Pages

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (UTC)
  workflow_dispatch:  # Allows manual trigger if needed

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Up Node.js (Optional, for Static Site Generators)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update Site Content
        run: |
          echo "Updating site at $(date)" > docs/last_updated.txt
          python src/api/check_status.py
          git add docs/last_updated.txt docs/flag_status.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git commit -m "Automated update at $(date)" || exit 0
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Deploy the docs directory